#!/bin/sh /etc/rc.common

START=99
STOP=10

SS_CONF="/etc/shadowsocks-libev/config.json"
SS_REDIR_PID="/var/run/ss-redir.pid"
CHNROUTE="/etc/shadowsocks-libev/chnroute.txt"

start() {
    if grep -q "YOUR_SERVER" "$SS_CONF"; then
        echo "Please edit $SS_CONF first"
        return 1
    fi

    ss-redir -c "$SS_CONF" -f "$SS_REDIR_PID"
    setup_nftables
    setup_dns
}

stop() {
    restore_dns
    cleanup_nftables
    kill "$(cat "$SS_REDIR_PID" 2>/dev/null)" 2>/dev/null
    rm -f "$SS_REDIR_PID"
}

get_server_ip() {
    jsonfilter -i "$SS_CONF" -e '@.server'
}

setup_dns() {
    uci set dhcp.@dnsmasq[0].noresolv='1'
    uci -q delete dhcp.@dnsmasq[0].server
    uci add_list dhcp.@dnsmasq[0].server='8.8.8.8'
    uci add_list dhcp.@dnsmasq[0].server='8.8.4.4'
    uci commit dhcp
    /etc/init.d/dnsmasq restart
}

restore_dns() {
    uci -q delete dhcp.@dnsmasq[0].noresolv
    uci -q delete dhcp.@dnsmasq[0].server
    uci commit dhcp
    /etc/init.d/dnsmasq restart
}

setup_nftables() {
    local server_ip
    server_ip=$(get_server_ip)

    nft add table ip ss
    nft add chain ip ss prerouting { type nat hook prerouting priority -100 \; }

    # Skip private/reserved
    nft add rule ip ss prerouting ip daddr { 0.0.0.0/8, 10.0.0.0/8, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.168.0.0/16, 224.0.0.0/4, 240.0.0.0/4 } return

    # Skip SS server
    [ -n "$server_ip" ] && nft add rule ip ss prerouting ip daddr "$server_ip" return

    # Load chnroute
    if [ -f "$CHNROUTE" ]; then
        nft add set ip ss chnroute { type ipv4_addr \; flags interval \; }
        local elements
        elements=$(sed ':a;N;$!ba;s/\n/, /g' "$CHNROUTE")
        nft add element ip ss chnroute { $elements }
        nft add rule ip ss prerouting ip daddr @chnroute return
    fi

    # Redirect TCP (except SSH) to ss-redir
    nft add rule ip ss prerouting tcp dport != 22 redirect to :1080
}

cleanup_nftables() {
    nft delete table ip ss 2>/dev/null
}
